# left-side user profile
avatar: /img/avatar.jpg# by default https://octodex.github.com/images/baracktocat.jpg
location: Internet
email: romdev@vivaldi.net
social:
  github: https://github.com/rom0dev/
  telegram: https://t.me/RobotIsHere
  linkedin: https://www.linkedin.com/in/rominsky/

# navbar menu
menu:
 archives: false
 tags: false
 categories: false

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx
